[console]
depends = [
  "bat",
  "helix",
  "shell",
  "starship",
  "zellij"
]

[console.files]
ssh_config = "~/.ssh/config"

[graphics]
depends = [
  "alacritty"
]

[graphics.files]
"locale.conf" = "~/.config/locale.conf"
"mimeapps.list" = "~/.config/mimeapps.list"
"user-dirs.dirs" = "~/.config/user-dirs.dirs"
# custom binaries
"bin/auto-theme-switch.sh" = "~/.local/bin/auto-theme-switch"
# applications to start
# "autostart/auto-theme-switch.desktop" = "~/.config/autostart/auto-theme-switch.desktop"
"containers/syncthing.container" = "~/.config/containers/systemd/syncthing.container"

[work]
depends = [
  "development",
  "devops",
  "helix"
]


[alacritty]

[alacritty.files]
"alacritty/alacritty.toml" = "~/.config/alacritty/alacritty.toml"
"alacritty/themes/themes/gruvbox_dark.toml" = "~/.config/alacritty/themes/gruvbox_dark.toml"
"alacritty/themes/themes/gruvbox_light.toml" = "~/.config/alacritty/themes/gruvbox_light.toml"

[bat.files]
"bat/config" = "~/.config/bat/config"

[development.files]
"git/config" = "~/.gitconfig"
"git/gitignore_global" = "~/.gitignore_global"
npmrc = "~/.npmrc"
"bin/virtualenv.sh" = "~/.local/bin/venv"

[devops.files]
"k9s/skin.yaml" = "~/.config/k9s/skin.yml"
"bin/kubectl-finalizers_remove.sh" = "~/.local/bin/kubectl-finalizers_remove"

[helix.files]
"helix/config.toml" = "~/.config/helix/config.toml"
"helix/languages.toml" = "~/.config/helix/languages.toml"

[shell.files]
dircolors = "~/.dircolors"
# custom binaries
"bin/pdf-shrink.sh" = "~/.local/bin/pdf-shrink"
"bin/search-and-launch.sh" = "~/.local/bin/seaunch"
"bin/ssh-prepare.sh" = "~/.local/bin/ssh-prepare"
# profile (common files)
"shell/profile.sh" = "~/.profile"
"shell/profile.d/aliases.sh" = "~/.config/profile/aliases.sh"
"shell/profile.d/completion.sh" = "~/.config/profile/completion.sh"
"shell/profile.d/env.sh" = "~/.config/profile/env.sh"
"shell/profile.d/lc.sh" = "~/.config/profile/lc.sh"
"shell/profile.d/path.sh" = "~/.config/profile/path.sh"
"shell/profile.d/ssh_agent.sh" = "~/.config/profile/ssh_agent.sh"
"shell/profile.d/tools.sh" = "~/.config/profile/tools.sh"
# Bash files
"shell/bashrc.bash" = "~/.bashrc"
# ZSH files
"shell/zshrc.zsh" = "~/.zshrc"
"shell/zsh/abbreviations.zsh" = "~/.zsh/abbreviations.zsh"
"shell/zsh/completion.zsh" = "~/.zsh/completion.zsh"
"shell/zsh/map.zsh" = "~/.zsh/map.zsh"
"shell/zsh/plugins.zsh" = "~/.zsh/plugins.zsh"
# Fish files
"shell/fish.fish" = "~/.config/fish/config.fish"

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[zellij.files]
"bin/zellij-shortcut.sh" = "~/.local/bin/zj" # custom command
"zellij/config.kdl" = "~/.config/zellij/config.kdl"
"zellij/layout/default.yaml" = "~/.config/zellij/layout/default.yaml"
"zellij/layout/updates.yaml" = "~/.config/zellij/layout/updates.yaml"
