[console]
depends = [
  "bat",
  "helix",
  "shell",
  "starship",
  "zellij"
]

[console.files]
ssh_config = "~/.ssh/config"

[graphics]
depends = [
  "alacritty"
]

[graphics.files]
"locale.conf" = "~/.config/locale.conf"
"mimeapps.list" = "~/.config/mimeapps.list"
"user-dirs.dirs" = "~/.config/user-dirs.dirs"
# systemd units
"systemd-units/syncthing.service" = "~/.config/systemd/user/syncthing.service"

[work]
depends = [
  "development",
  "devops",
  "helix"
]


[alacritty]

[alacritty.files]
"alacritty/alacritty.toml" = "~/.config/alacritty/alacritty.toml"
"alacritty/themes/themes/gruvbox_dark.toml" = "~/.config/alacritty/themes/gruvbox_dark.toml"
"alacritty/themes/themes/gruvbox_light.toml" = "~/.config/alacritty/themes/gruvbox_light.toml"

[bat.files]
"bat/config" = "~/.config/bat/config"

[development.files]
"git/config" = "~/.gitconfig"
"git/gitignore_global" = "~/.gitignore_global"
npmrc = "~/.npmrc"

[devops.files]
"k9s/skin.yaml" = "~/.config/k9s/skin.yml"

[helix.files]
"helix/config.toml" = "~/.config/helix/config.toml"
"helix/languages.toml" = "~/.config/helix/languages.toml"

[shell.files]
dircolors = "~/.dircolors"
# profile (common files)
"shell/profile.sh" = "~/.profile"
"shell/profile.d/aliases.sh" = "~/.config/profile/aliases.sh"
"shell/profile.d/completion.sh" = "~/.config/profile/completion.sh"
"shell/profile.d/env.sh" = "~/.config/profile/env.sh"
"shell/profile.d/lc.sh" = "~/.config/profile/lc.sh"
"shell/profile.d/path.sh" = "~/.config/profile/path.sh"
"shell/profile.d/ssh_agent.sh" = "~/.config/profile/ssh_agent.sh"
"shell/profile.d/tools.sh" = "~/.config/profile/tools.sh"
# Bash files
"shell/bashrc.sh" = "~/.bashrc"
# ZSH files
"shell/zshrc.sh" = "~/.zshrc"
"shell/zsh/abbreviations.zsh" = "~/.zsh/abbreviations.zsh"
"shell/zsh/completion.zsh" = "~/.zsh/completion.zsh"
"shell/zsh/hooks.zsh" = "~/.zsh/hooks.zsh"
"shell/zsh/map.zsh" = "~/.zsh/map.zsh"
"shell/zsh/plugins.zsh" = "~/.zsh/plugins.zsh"
# Fish files
"shell/fish.fish" = "~/.config/fish/config.fish"

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[zellij.files]
"shell/profile.d/zellij.sh" = "~/.config/profile/zellij.sh" # Zellij shortcuts
"zellij/config.kdl" = "~/.config/zellij/config.kdl"
"zellij/layout/default.yaml" = "~/.config/zellij/layout/default.yaml"
"zellij/layout/updates.yaml" = "~/.config/zellij/layout/updates.yaml"
